name = "ParallelDifferentialEvolution"
uuid = "37290534-901f-4f6f-9784-d8c4e32b862a"
authors = ["John Travers <jtravs@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
